In [2]:
# https://www.kaggle.com/competitions/spaceship-titanic/overview
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns

train = pd.read_csv("./data/train.csv")
test = pd.read_csv("./data/test.csv")
sample = pd.read_csv("./data/sample_submission.csv",header=None)


                0            1
0     PassengerId  Transported
1         0013_01        False
2         0018_01        False
3         0019_01        False
4         0021_01        False
...           ...          ...
4273      9266_02        False
4274      9269_01        False
4275      9271_01        False
4276      9273_01        False
4277      9277_01        False

[4278 rows x 2 columns]


In [2]:
# trainデータの先頭行を表示
train.head()

PassengerId HomePlanet CryoSleep  Cabin  Destination   Age    VIP  \
0     0001_01     Europa     False  B/0/P  TRAPPIST-1e  39.0  False   
1     0002_01      Earth     False  F/0/S  TRAPPIST-1e  24.0  False   
2     0003_01     Europa     False  A/0/S  TRAPPIST-1e  58.0   True   
3     0003_02     Europa     False  A/0/S  TRAPPIST-1e  33.0  False   
4     0004_01      Earth     False  F/1/S  TRAPPIST-1e  16.0  False   

   RoomService  FoodCourt  ShoppingMall     Spa  VRDeck               Name  \
0          0.0        0.0           0.0     0.0     0.0    Maham Ofracculy   
1        109.0        9.0          25.0   549.0    44.0       Juanna Vines   
2         43.0     3576.0           0.0  6715.0    49.0      Altark Susent   
3          0.0     1283.0         371.0  3329.0   193.0       Solam Susent   
4        303.0       70.0         151.0   565.0     2.0  Willy Santantines   

   Transported  
0        False  
1         True  
2        False  
3        False  
4         True

In [3]:
# testデータの先頭行を表示
test.head()

PassengerId HomePlanet CryoSleep  Cabin  Destination   Age    VIP  \
0     0013_01      Earth      True  G/3/S  TRAPPIST-1e  27.0  False   
1     0018_01      Earth     False  F/4/S  TRAPPIST-1e  19.0  False   
2     0019_01     Europa      True  C/0/S  55 Cancri e  31.0  False   
3     0021_01     Europa     False  C/1/S  TRAPPIST-1e  38.0  False   
4     0023_01      Earth     False  F/5/S  TRAPPIST-1e  20.0  False   

   RoomService  FoodCourt  ShoppingMall     Spa  VRDeck              Name  
0          0.0        0.0           0.0     0.0     0.0   Nelly Carsoning  
1          0.0        9.0           0.0  2823.0     0.0    Lerome Peckers  
2          0.0        0.0           0.0     0.0     0.0   Sabih Unhearfus  
3          0.0     6652.0           0.0   181.0   585.0  Meratz Caltilter  
4         10.0        0.0         635.0     0.0     0.0   Brence Harperez

In [4]:
# trainデータの統計的な情報を表示
train.describe()

Age   RoomService     FoodCourt  ShoppingMall           Spa  \
count  8514.000000   8512.000000   8510.000000   8485.000000   8510.000000   
mean     28.827930    224.687617    458.077203    173.729169    311.138778   
std      14.489021    666.717663   1611.489240    604.696458   1136.705535   
min       0.000000      0.000000      0.000000      0.000000      0.000000   
25%      19.000000      0.000000      0.000000      0.000000      0.000000   
50%      27.000000      0.000000      0.000000      0.000000      0.000000   
75%      38.000000     47.000000     76.000000     27.000000     59.000000   
max      79.000000  14327.000000  29813.000000  23492.000000  22408.000000   

             VRDeck  
count   8505.000000  
mean     304.854791  
std     1145.717189  
min        0.000000  
25%        0.000000  
50%        0.000000  
75%       46.000000  
max    24133.000000

In [5]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   PassengerId   8693 non-null   object 
 1   HomePlanet    8492 non-null   object 
 2   CryoSleep     8476 non-null   object 
 3   Cabin         8494 non-null   object 
 4   Destination   8511 non-null   object 
 5   Age           8514 non-null   float64
 6   VIP           8490 non-null   object 
 7   RoomService   8512 non-null   float64
 8   FoodCourt     8510 non-null   float64
 9   ShoppingMall  8485 non-null   float64
 10  Spa           8510 non-null   float64
 11  VRDeck        8505 non-null   float64
 12  Name          8493 non-null   object 
 13  Transported   8693 non-null   bool   
dtypes: bool(1), float64(6), object(7)
memory usage: 891.5+ KB


In [6]:
train['Transported'].value_counts()

True     4378
False    4315
Name: Transported, dtype: int64

In [6]:
print(train["HomePlanet"].unique())
print(train["CryoSleep"].unique())
print(train["Cabin"].unique())
print(train["Destination"].unique())
print(train["Age"].unique())
print(train["VIP"].unique())
print(train["RoomService"].unique())
print(train["FoodCourt"].unique())
print(train["ShoppingMall"].unique())
print(train["Spa"].unique())
print(train["VRDeck"].unique())
print(train["Name"].unique())

['Europa' 'Earth' 'Mars' nan]
[False True nan]
['B/0/P' 'F/0/S' 'A/0/S' ... 'G/1499/S' 'G/1500/S' 'E/608/S']
['TRAPPIST-1e' 'PSO J318.5-22' '55 Cancri e' nan]
[39. 24. 58. 33. 16. 44. 26. 28. 35. 14. 34. 45. 32. 48. 31. 27.  0.  1.
 49. 29. 10.  7. 21. 62. 15. 43. 47.  2. 20. 23. 30. 17. 55.  4. 19. 56.
 nan 25. 38. 36. 22. 18. 42. 37. 13.  8. 40.  3. 54.  9.  6. 64. 67. 61.
 50. 41. 57. 11. 52. 51. 46. 60. 63. 59.  5. 79. 68. 74. 12. 53. 65. 71.
 75. 70. 76. 78. 73. 66. 69. 72. 77.]
[False True nan]
[   0.  109.   43. ... 1569. 8586.  745.]
[   0.    9. 3576. ... 3208. 6819. 4688.]
[   0.   25.  371. ... 1085.  510. 1872.]
[   0.  549. 6715. ... 2868. 1107. 1643.]
[   0.   44.   49. ... 1164.  971. 3235.]
['Maham Ofracculy' 'Juanna Vines' 'Altark Susent' ... 'Fayey Connon'
 'Celeon Hontichre' 'Propsh Hontichre']


In [7]:
# 一応NULL値ないか確認
print(train.isnull().sum())

PassengerId       0
HomePlanet      201
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64


In [9]:
df2 = train.dropna(how='all').dropna(how='all', axis=1)
print(df2)
df2.info()

     PassengerId HomePlanet CryoSleep     Cabin    Destination   Age    VIP  \
0        0001_01     Europa     False     B/0/P    TRAPPIST-1e  39.0  False   
1        0002_01      Earth     False     F/0/S    TRAPPIST-1e  24.0  False   
2        0003_01     Europa     False     A/0/S    TRAPPIST-1e  58.0   True   
3        0003_02     Europa     False     A/0/S    TRAPPIST-1e  33.0  False   
4        0004_01      Earth     False     F/1/S    TRAPPIST-1e  16.0  False   
...          ...        ...       ...       ...            ...   ...    ...   
8688     9276_01     Europa     False    A/98/P    55 Cancri e  41.0   True   
8689     9278_01      Earth      True  G/1499/S  PSO J318.5-22  18.0  False   
8690     9279_01      Earth     False  G/1500/S    TRAPPIST-1e  26.0  False   
8691     9280_01     Europa     False   E/608/S    55 Cancri e  32.0  False   
8692     9280_02     Europa     False   E/608/S    TRAPPIST-1e  44.0  False   

      RoomService  FoodCourt  ShoppingMall     Spa 

In [17]:
########## 2回目
import pandas as pd
import numpy as np

train = pd.read_csv('./data/train.csv', index_col=0)
test = pd.read_csv('./data/test.csv', index_col=0)
sample_submit = pd.read_csv('./data/sample_submission.csv', index_col=0)
print(sample_submit)
from sklearn.model_selection import train_test_split
# from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import f1_score

def label_encoding(data):
    '''
    カテゴリーをLabelエンコーディング
    '''
    LE = LabelEncoder()
    LE.fit_transform(data.values)
    return LE.fit_transform(data.values)

# nanの行列を削除
df2 = train.dropna(how='any').dropna(how='any', axis=1)
# print(df2)
# print(df2.isnull().sum())

# df2 を変換
df2["HomePlanet"] = label_encoding(df2["HomePlanet"])
df2["CryoSleep"] = label_encoding(df2["CryoSleep"])
df2["Cabin"] = label_encoding(df2["Cabin"])
df2["Destination"] = label_encoding(df2["Destination"])
df2["VIP"] = label_encoding(df2["VIP"])
df2["Name"] = label_encoding(df2["Name"])

# test を変換
test["HomePlanet"] = label_encoding(test["HomePlanet"])
test["CryoSleep"] = label_encoding(test["CryoSleep"])
test["Cabin"] = label_encoding(test["Cabin"])
test["Destination"] = label_encoding(test["Destination"])
test["VIP"] = label_encoding(test["VIP"])
test["Name"] = label_encoding(test["Name"])

# 訓練データとテストデータに分割
# stratifyを設定して目的変数の分布を保ったまま分割
train, valid = train_test_split(df2, test_size=0.2, stratify=df2['Transported'], random_state=82)

# 目的変数とそれ以外に学習用データを分割
x_train = train.drop(columns=['Transported']) 
y_train = train['Transported']
x_valid = valid.drop(columns=['Transported']) 
y_valid = valid['Transported']
x_test = test

# モデルを作成して訓練
# model = LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=1000)
model = HistGradientBoostingClassifier(max_iter=1000)
model.fit(x_train, y_train)

# validの特徴量で予測
valid_predictions = model.predict(x_valid)
valid_f1 = f1_score(y_valid, valid_predictions, average='macro')
print(f"Validation F1 Score (Macro): {valid_f1}")

# 予測結果をCSVファイルとして保存
pred = model.predict(x_test)
print(pred)
# sample_submit[0] = ['PassengerId', 'Transported']
sample_submit[1] = pred
sample_submit.to_csv('./submit/submit2.csv')

             Transported
PassengerId             
0013_01            False
0018_01            False
0019_01            False
0021_01            False
0023_01            False
...                  ...
9266_02            False
9269_01            False
9271_01            False
9273_01            False
9277_01            False

[4277 rows x 1 columns]
Validation F1 Score (Macro): 0.7798788453054701
[ True False  True ...  True  True  True]
